revoke delete on table "public"."matches" from "anon";

revoke insert on table "public"."matches" from "anon";

revoke references on table "public"."matches" from "anon";

revoke select on table "public"."matches" from "anon";

revoke trigger on table "public"."matches" from "anon";

revoke truncate on table "public"."matches" from "anon";

revoke update on table "public"."matches" from "anon";

revoke delete on table "public"."matches" from "authenticated";

revoke insert on table "public"."matches" from "authenticated";

revoke references on table "public"."matches" from "authenticated";

revoke select on table "public"."matches" from "authenticated";

revoke trigger on table "public"."matches" from "authenticated";

revoke truncate on table "public"."matches" from "authenticated";

revoke update on table "public"."matches" from "authenticated";

revoke delete on table "public"."matches" from "service_role";

revoke insert on table "public"."matches" from "service_role";

revoke references on table "public"."matches" from "service_role";

revoke select on table "public"."matches" from "service_role";

revoke trigger on table "public"."matches" from "service_role";

revoke truncate on table "public"."matches" from "service_role";

revoke update on table "public"."matches" from "service_role";

alter table "public"."matches" drop constraint "matches_away_team_id_fkey";

alter table "public"."matches" drop constraint "matches_home_team_id_fkey";

alter table "public"."matches" drop constraint "matches_season_id_fkey";

alter table "public"."matches" drop constraint "matches_pkey";

alter table "public"."teams" drop constraint "teams_pkey";

drop index if exists "public"."matches_pkey";

drop index if exists "public"."teams_pkey";

drop table "public"."matches";


  create table "public"."contacts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "phone_number" text
      );



  create table "public"."games" (
    "id" bigint generated by default as identity not null,
    "season_id" bigint,
    "home_team_id" bigint,
    "away_team_id" bigint,
    "home_score" integer default 0,
    "away_score" integer default 0,
    "start_date" timestamp with time zone,
    "group_id" bigint,
    "referee_team_id" bigint,
    "referee_absent" boolean,
    "comment" text,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "season_id" bigint
      );



  create table "public"."programs" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."seasons" add column "end_date" timestamp with time zone;

alter table "public"."seasons" add column "start_date" timestamp with time zone;

alter table "public"."teams" add column "primary_contact_id" bigint;

alter table "public"."teams" add column "program_id" bigint;

alter table "public"."teams" add column "season_id" bigint;

alter table "public"."teams" add column "secondary_contact_id" bigint;

alter table "public"."teams" alter column "created_at" set not null;

alter table "public"."teams" alter column "name" drop not null;

CREATE UNIQUE INDEX contact_persons_pkey ON public.contacts USING btree (id);

CREATE UNIQUE INDEX groups_pkey ON public.groups USING btree (id);

CREATE UNIQUE INDEX team_registrations_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX matches_pkey ON public.games USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.programs USING btree (id);

alter table "public"."contacts" add constraint "contact_persons_pkey" PRIMARY KEY using index "contact_persons_pkey";

alter table "public"."games" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "public"."programs" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."teams" add constraint "team_registrations_pkey" PRIMARY KEY using index "team_registrations_pkey";

alter table "public"."games" add constraint "games_referee_team_id_fkey" FOREIGN KEY (referee_team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."games" validate constraint "games_referee_team_id_fkey";

alter table "public"."games" add constraint "matches_away_team_id_fkey" FOREIGN KEY (away_team_id) REFERENCES public.programs(id) ON DELETE CASCADE not valid;

alter table "public"."games" validate constraint "matches_away_team_id_fkey";

alter table "public"."games" add constraint "matches_group_id_fkey" FOREIGN KEY (group_id) REFERENCES public.groups(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."games" validate constraint "matches_group_id_fkey";

alter table "public"."games" add constraint "matches_home_team_id_fkey" FOREIGN KEY (home_team_id) REFERENCES public.programs(id) ON DELETE CASCADE not valid;

alter table "public"."games" validate constraint "matches_home_team_id_fkey";

alter table "public"."games" add constraint "matches_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."games" validate constraint "matches_season_id_fkey";

alter table "public"."groups" add constraint "groups_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."groups" validate constraint "groups_season_id_fkey";

alter table "public"."teams" add constraint "team_registrations_primary_contact_id_fkey" FOREIGN KEY (primary_contact_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."teams" validate constraint "team_registrations_primary_contact_id_fkey";

alter table "public"."teams" add constraint "team_registrations_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id) not valid;

alter table "public"."teams" validate constraint "team_registrations_season_id_fkey";

alter table "public"."teams" add constraint "team_registrations_secondary_contact_id_fkey" FOREIGN KEY (secondary_contact_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."teams" validate constraint "team_registrations_secondary_contact_id_fkey";

alter table "public"."teams" add constraint "teams_program_id_fkey" FOREIGN KEY (program_id) REFERENCES public.programs(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."teams" validate constraint "teams_program_id_fkey";

grant delete on table "public"."contacts" to "anon";

grant insert on table "public"."contacts" to "anon";

grant references on table "public"."contacts" to "anon";

grant select on table "public"."contacts" to "anon";

grant trigger on table "public"."contacts" to "anon";

grant truncate on table "public"."contacts" to "anon";

grant update on table "public"."contacts" to "anon";

grant delete on table "public"."contacts" to "authenticated";

grant insert on table "public"."contacts" to "authenticated";

grant references on table "public"."contacts" to "authenticated";

grant select on table "public"."contacts" to "authenticated";

grant trigger on table "public"."contacts" to "authenticated";

grant truncate on table "public"."contacts" to "authenticated";

grant update on table "public"."contacts" to "authenticated";

grant delete on table "public"."contacts" to "service_role";

grant insert on table "public"."contacts" to "service_role";

grant references on table "public"."contacts" to "service_role";

grant select on table "public"."contacts" to "service_role";

grant trigger on table "public"."contacts" to "service_role";

grant truncate on table "public"."contacts" to "service_role";

grant update on table "public"."contacts" to "service_role";

grant delete on table "public"."games" to "anon";

grant insert on table "public"."games" to "anon";

grant references on table "public"."games" to "anon";

grant select on table "public"."games" to "anon";

grant trigger on table "public"."games" to "anon";

grant truncate on table "public"."games" to "anon";

grant update on table "public"."games" to "anon";

grant delete on table "public"."games" to "authenticated";

grant insert on table "public"."games" to "authenticated";

grant references on table "public"."games" to "authenticated";

grant select on table "public"."games" to "authenticated";

grant trigger on table "public"."games" to "authenticated";

grant truncate on table "public"."games" to "authenticated";

grant update on table "public"."games" to "authenticated";

grant delete on table "public"."games" to "service_role";

grant insert on table "public"."games" to "service_role";

grant references on table "public"."games" to "service_role";

grant select on table "public"."games" to "service_role";

grant trigger on table "public"."games" to "service_role";

grant truncate on table "public"."games" to "service_role";

grant update on table "public"."games" to "service_role";

grant delete on table "public"."groups" to "anon";

grant insert on table "public"."groups" to "anon";

grant references on table "public"."groups" to "anon";

grant select on table "public"."groups" to "anon";

grant trigger on table "public"."groups" to "anon";

grant truncate on table "public"."groups" to "anon";

grant update on table "public"."groups" to "anon";

grant delete on table "public"."groups" to "authenticated";

grant insert on table "public"."groups" to "authenticated";

grant references on table "public"."groups" to "authenticated";

grant select on table "public"."groups" to "authenticated";

grant trigger on table "public"."groups" to "authenticated";

grant truncate on table "public"."groups" to "authenticated";

grant update on table "public"."groups" to "authenticated";

grant delete on table "public"."groups" to "service_role";

grant insert on table "public"."groups" to "service_role";

grant references on table "public"."groups" to "service_role";

grant select on table "public"."groups" to "service_role";

grant trigger on table "public"."groups" to "service_role";

grant truncate on table "public"."groups" to "service_role";

grant update on table "public"."groups" to "service_role";

grant delete on table "public"."programs" to "anon";

grant insert on table "public"."programs" to "anon";

grant references on table "public"."programs" to "anon";

grant select on table "public"."programs" to "anon";

grant trigger on table "public"."programs" to "anon";

grant truncate on table "public"."programs" to "anon";

grant update on table "public"."programs" to "anon";

grant delete on table "public"."programs" to "authenticated";

grant insert on table "public"."programs" to "authenticated";

grant references on table "public"."programs" to "authenticated";

grant select on table "public"."programs" to "authenticated";

grant trigger on table "public"."programs" to "authenticated";

grant truncate on table "public"."programs" to "authenticated";

grant update on table "public"."programs" to "authenticated";

grant delete on table "public"."programs" to "service_role";

grant insert on table "public"."programs" to "service_role";

grant references on table "public"."programs" to "service_role";

grant select on table "public"."programs" to "service_role";

grant trigger on table "public"."programs" to "service_role";

grant truncate on table "public"."programs" to "service_role";

grant update on table "public"."programs" to "service_role";


