alter table "public"."contacts" drop constraint "contacts_team_id_fkey";


  create table "public"."team_contacts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "team_id" bigint,
    "contact_id" bigint
      );


alter table "public"."contacts" drop column "team_id";

alter table "public"."contacts" add column "fallback_name" text;

alter table "public"."contacts" add column "fallback_phone" text;

CREATE UNIQUE INDEX team_contacts_pkey ON public.team_contacts USING btree (id);

alter table "public"."team_contacts" add constraint "team_contacts_pkey" PRIMARY KEY using index "team_contacts_pkey";

alter table "public"."team_contacts" add constraint "team_contacts_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."team_contacts" validate constraint "team_contacts_contact_id_fkey";

alter table "public"."team_contacts" add constraint "team_contacts_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."team_contacts" validate constraint "team_contacts_team_id_fkey";

grant delete on table "public"."team_contacts" to "anon";

grant insert on table "public"."team_contacts" to "anon";

grant references on table "public"."team_contacts" to "anon";

grant select on table "public"."team_contacts" to "anon";

grant trigger on table "public"."team_contacts" to "anon";

grant truncate on table "public"."team_contacts" to "anon";

grant update on table "public"."team_contacts" to "anon";

grant delete on table "public"."team_contacts" to "authenticated";

grant insert on table "public"."team_contacts" to "authenticated";

grant references on table "public"."team_contacts" to "authenticated";

grant select on table "public"."team_contacts" to "authenticated";

grant trigger on table "public"."team_contacts" to "authenticated";

grant truncate on table "public"."team_contacts" to "authenticated";

grant update on table "public"."team_contacts" to "authenticated";

grant delete on table "public"."team_contacts" to "service_role";

grant insert on table "public"."team_contacts" to "service_role";

grant references on table "public"."team_contacts" to "service_role";

grant select on table "public"."team_contacts" to "service_role";

grant trigger on table "public"."team_contacts" to "service_role";

grant truncate on table "public"."team_contacts" to "service_role";

grant update on table "public"."team_contacts" to "service_role";


